### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by mrprovoker** [Babeev/Validity_Praktitum#7]
Добрый день.

Данные регулярки покрыли много проверок, но, к сожалению, работа учитывает не все пункты задания. Необходимо исправить.

**Надо исправить:**
- В README необходимо добавить описание и ссылку на проект на github.io.
- Проходит валидацию имя записанное капсом: `ЯННННН`
- Проходит валидацию такие невалидные имена: `Ян-`, Ян-Я`
- Не проходит проверку валидный email: `mysite@you.me.net`
- Проходит валидацию такой невалидный почтовый ящик `mysite123@gmail.b` (tld не может быть однобуквенным) или `mysite123@gmail.32` (tld не может состоять из цифр). Также не может начинаться с точки.
- Проходит такой невалидный телефон: `+7(925 900-90-90`. 
- Проходит валидацию такой невалиднaй IP-адрес: `http://www.255.255.255.255`, `http://255.255.245.0356`, `http://255.255.32`. В ip-адресе должно быть ровно 4 группы, допустимые значения каждой группы от 0 до 255.
- Проходит url с портом: `https://mysite.ru:80000000` или `http://mysite.ru:8`. Согласно заданию: `порт — тоже необязательная группа. Порт начинается с двоеточия, за которым идут **от 2 до 5 цифр**`
Также стоит учесть, что из определения максимальный существующий порт - 65535, а все что больше - невалидный.

После исправлений замечаний необходимо убедиться, что все пункты задания выполнены, все проверки проходят по ссылке проекта на github.io.

Работу смогу принять только после устранения всех замечаний из пункта Надо исправить.

**Comment by Babeev** [comment]
Готово

**Comment by mrprovoker** [comment]
@Babeev  cпасибо за правки. Теперь все хорошо.

Предлагаю самостоятельно решить одну из появившихся проблем:
- Сейчас последняя цифра в IP-группе не может быть больше 5. Например, не проходит такой валидный адрес: `http://255.255.255.156`

---
Все остальные пункты задания выполнены в полном объеме. Задание **принято** 👍

*Желаю успехов в дальнейшем обучении!*
